package com.deadzone.audio;

import android.content.Context;
import android.media.SoundPool;

import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

/** All game audio: original procedurally-synthesized WAVs bundled in assets
 *  (generated by tools/make_audio.py — no third-party assets). Short effects
 *  through SoundPool; rain/ambience as loops. Assets are extracted once to
 *  internal storage so SoundPool can load them by file URI. */
public class AudioMgr {
    public static final String[] NAMES = {
            "shot_rifle", "shot_smg", "shot_shotgun", "shot_sniper",
            "reload", "empty", "swap", "zdie", "scream", "hurt", "die",
            "med", "pickup", "interact", "deny", "wave",
            "boss_roar", "boss_slam", "boss_charge", "boss_wind", "ui",
            "rain", "drone",
    };

    private SoundPool sp;
    private final Map<String, Integer> ids = new HashMap<String, Integer>();
    private final Set<Integer> active = new HashSet<Integer>();
    private float vol = 1f;
    private boolean ready;
    private int rainStream = -1, droneStream = -1;
    private boolean rainOn, droneOn;
    private boolean paused;

    public void init(Context ctx) {
        sp = new SoundPool.Builder().setMaxStreams(12).build();
        Thread t = new Thread(new Runnable() {
            @Override public void run() {
                try {
                    File dir = new File(ctx.getFilesDir(), "audio");
                    if (!dir.isDirectory()) dir.mkdirs();
                    for (String n : NAMES) {
                        File f = new File(dir, n + ".wav");
                        if (!f.exists() || f.length() == 0) {
                            InputStream in = ctx.getAssets().open("audio/" + n + ".wav");
                            FileOutputStream out = new FileOutputStream(f);
                            byte[] buf = new byte[8192];
                            int k;
                            while ((k = in.read(buf)) > 0) out.write(buf, 0, k);
                            out.close();
                            in.close();
                        }
                        int id = sp.load("file://" + f.getAbsolutePath(), 1);
                        if (id != 0) ids.put(n, id);
                    }
                    ready = true;
                    syncLoops();
                } catch (Exception e) {
                    // audio is non-fatal
                }
            }
        });
        t.setPriority(Thread.MIN_PRIORITY);
        t.start();
    }

    public void play(String n) { play(n, 1f, 1f); }

    public void play(String n, float v, float rate) {
        if (sp == null || !ready || paused) return;
        Integer id = ids.get(n);
        if (id == null) return;
        float vlv = Math.max(0.05f, vol * v);
        int stream = sp.play(id, vlv, vlv, 1, 0, rate);
        if (stream >= 0) active.add(stream);
    }

    public void setRain(boolean on) { rainOn = on; syncLoops(); }
    public void setDrone(boolean on) { droneOn = on; syncLoops(); }

    private void syncLoops() {
        if (sp == null || !ready || paused) return;
        if (rainOn && rainStream < 0 && ids.containsKey("rain")) {
            rainStream = sp.play(ids.get("rain"), vol * 0.45f, vol * 0.45f, 1, -1, 1f);
            if (rainStream >= 0) active.add(rainStream);
        }
        if (!rainOn && rainStream >= 0) { sp.stop(rainStream); active.remove(rainStream); rainStream = -1; }
        if (droneOn && droneStream < 0 && ids.containsKey("drone")) {
            droneStream = sp.play(ids.get("drone"), vol * 0.4f, vol * 0.4f, 2, -1, 1f);
            if (droneStream >= 0) active.add(droneStream);
        }
        if (!droneOn && droneStream >= 0) { sp.stop(droneStream); active.remove(droneStream); droneStream = -1; }
    }

    public void setVol(float v) {
        vol = v;
        // restart loops so volume applies
        rainStream = -1; droneStream = -1;
        boolean r = rainOn, d = droneOn;
        rainOn = false; droneOn = false;
        syncLoops();
        rainOn = r; droneOn = d;
        syncLoops();
    }

    public void pauseAll() {
        if (sp == null) return;
        paused = true;
        for (Integer s : active) sp.pause(s);
    }

    public void resumeAll() {
        if (sp == null) return;
        paused = false;
        for (Integer s : active) sp.resume(s);
    }

    public void release() {
        if (sp != null) sp.release();
        sp = null;
        ids.clear();
        active.clear();
    }
}
